'use client';
import {useMemo,useRef,useState} from 'react';
import {parseCsv,readiness,evidenceLevel,summarizeCampaigns,reconcile,experimentStats,budgetPlan,decisionFor} from '../lib/analytics.mjs';

type Row=Record<string,string>;
type RevenueBasis='auto'|'platform'|'internal';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const demo=`date,channel,campaign,spend,revenue,internal_revenue,conversions,impressions,clicks\n2026-07-01,Google,Brand Search,8500,36500,33200,142,118000,7200\n2026-07-08,Google,Brand Search,9100,38200,34600,147,121000,7400\n2026-07-15,Google,Generic Search,14200,31800,28900,119,235000,8100\n2026-07-22,Google,Generic Search,15100,30100,27100,111,249000,7900\n2026-07-01,Meta,Prospecting,18800,34700,29200,126,410000,6200\n2026-07-08,Meta,Prospecting,20100,35100,29100,124,445000,6100\n2026-07-15,Meta,Retargeting,7600,28900,26300,108,98000,5100\n2026-07-22,Meta,Retargeting,7900,30100,27200,112,101000,5200\n2026-07-01,Email,CRM Winback,1800,15400,14800,72,42000,6400\n2026-07-08,Email,CRM Winback,1900,16100,15200,76,43800,6600`;

export default function Home(){
 const [rows,setRows]=useState<Row[]>([]),[name,setName]=useState(''),[margin,setMargin]=useState(.55),[budget,setBudget]=useState(90000),[basis,setBasis]=useState<RevenueBasis>('auto'),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState('');
 const firstFile=useRef<HTMLInputElement>(null), replaceFile=useRef<HTMLInputElement>(null);
 const ready=useMemo(()=>readiness(rows),[rows]), evidence=useMemo(()=>evidenceLevel(rows),[rows]), rec=useMemo(()=>reconcile(rows),[rows]);
 const campaigns=useMemo(()=>summarizeCampaigns(rows,margin,basis),[rows,margin,basis]);
 const exp=useMemo(()=>experimentStats(rows),[rows]), plan=useMemo(()=>budgetPlan(campaigns,budget),[campaigns,budget]);
 const totals=useMemo(()=>campaigns.reduce((a,c)=>({spend:a.spend+c.spend,revenue:a.revenue+c.revenue,contribution:a.contribution+c.contribution}),{spend:0,revenue:0,contribution:0}),[campaigns]);
 const resolvedBasis=campaigns[0]?.revenueBasis||'platform';
 const load=(text:string,label:string)=>{try{const r=parseCsv(text);if(!r.length)throw new Error('No usable rows found.');setRows(r);setName(label);setError('');setSelected(null);setBasis('auto');}catch(e){setError(e instanceof Error?e.message:'Could not read file');}};
 const onFile=async(f?:File)=>{if(!f)return;if(!f.name.toLowerCase().endsWith('.csv')){setError('Please upload a CSV export.');return;}load(await f.text(),f.name)};
 const exportMemo=()=>{const lines=['MEASUREMENT LADDER — DECISION MEMO',`Evidence strength: ${evidence.level}`,`Why: ${evidence.reason}`,`Readiness: ${ready.score}/100`,`Gross margin assumption: ${pct(margin)}`,`Decision revenue basis: ${resolvedBasis==='internal'?'internal/backend observed revenue':'platform-reported revenue'}`,'',...campaigns.map(c=>`${decisionFor(c)} — ${c.name}: spend ${money(c.spend)}, decision-basis revenue ${money(c.revenue)}, contribution ${money(c.contribution)}, ROAS ${c.roas.toFixed(2)}x`),'','Budget scenario:',...plan.map((p:{name:string;suggested:number;confidence:string})=>`${p.name}: ${money(p.suggested)} (${p.confidence} confidence)`),'','Important: decision cues and budget allocation are heuristics, not causal lift estimates.'];const blob=new Blob([lines.join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='measurement-decision-memo.txt';a.click();URL.revokeObjectURL(a.href)};
 return <main>
  <header className="top"><div><div className="eyebrow">DAY 09 · MARKETING DECISION SCIENCE</div><h1>Measurement <span>Ladder</span></h1><p>Marketing analytics that tells you <b>how strong your evidence is</b> before it tells you what to do.</p></div><div className="trust">Local CSV analysis<br/><strong>No database upload</strong></div></header>
  {!rows.length ? <section className="hero card"><div className="heroCopy"><div className="badge">Evidence before attribution</div><h2>Stop confusing platform reporting with proof.</h2><p>Upload campaign data. Measurement Ladder checks data quality, reconciles platform vs internal outcomes, limits the claim to the design your file can support, and turns it into a defensible decision memo.</p><div className="actions"><button className="btn primary" onClick={()=>firstFile.current?.click()}>Upload campaign CSV</button><input ref={firstFile} type="file" accept=".csv,text/csv" hidden onChange={e=>onFile(e.target.files?.[0])}/><button className="btn" onClick={()=>load(demo,'Interactive demo')}>Try interactive demo</button><a className="btn ghost" href="/sample.csv" download>Download template</a></div>{error&&<div className="error" role="alert" aria-live="polite">{error}</div>}</div><div className="ladder"><div className="rung off">4 · Experimental</div><div className="rung off">3 · Quasi-experimental candidate</div><div className="rung on">2 · Associational</div><div className="rung on">1 · Descriptive</div><small>Experimental status requires explicit randomized-assignment metadata plus a valid user/session denominator.</small></div></section>:
  <>
   <section className="workspaceHead"><div><div className="eyebrow">WORKSPACE · {name}</div><h2>Your measurement brief</h2></div><div className="actions"><button className="btn" onClick={()=>replaceFile.current?.click()}>Replace CSV</button><input ref={replaceFile} type="file" accept=".csv,text/csv" hidden onChange={e=>onFile(e.target.files?.[0])}/><button className="btn primary" onClick={exportMemo}>Export decision memo</button></div></section>
   <section className="signalGrid"><div className="card signal"><span>Evidence strength</span><strong className="evidence">{evidence.level}</strong><p>{evidence.reason}</p></div><div className="card signal"><span>Measurement readiness</span><strong>{ready.score}<i>/100</i></strong><div className="bar" aria-label={`Measurement readiness ${ready.score} out of 100`}><b style={{width:`${ready.score}%`}}/></div><p>{ready.issues[0]||'Core inputs are present.'}</p></div><div className="card signal"><span>Observed spend</span><strong>{money(totals.spend)}</strong><p>Known from uploaded rows</p></div><div className="card signal"><span>Contribution after media</span><strong>{money(totals.contribution)}</strong><p>Estimate using {pct(margin)} margin + <b>{resolvedBasis}</b> revenue</p></div></section>
   <section className="grid2"><div className="card panel"><div className="panelHead"><div><span className="kicker">KNOWN + ESTIMATED</span><h3>Campaign economics</h3></div><div className="controls"><label>Gross margin <b>{pct(margin)}</b><input aria-label="Gross margin assumption" type="range" min="0.1" max="0.9" step="0.05" value={margin} onChange={e=>setMargin(+e.target.value)}/></label>{rec.complete&&<label>Decision revenue basis <select aria-label="Decision revenue basis" value={basis} onChange={e=>setBasis(e.target.value as RevenueBasis)}><option value="auto">Auto · internal</option><option value="internal">Internal observed</option><option value="platform">Platform reported</option></select></label>}</div></div><div className="notice"><b>Decision basis: {resolvedBasis==='internal'?'internal/backend observed revenue':'platform-reported revenue'}.</b> {rec.complete?'You can override it for sensitivity analysis.':'Internal revenue is incomplete or unavailable, so the app will not silently mix revenue bases.'}</div><div className="table"><div className="tr th"><span>Campaign</span><span>Spend</span><span>ROAS</span><span>Contribution</span><span>Decision</span></div>{campaigns.map(c=><button className={`tr ${selected===c.name?'sel':''}`} key={c.name} onClick={()=>setSelected(c.name)}><span>{c.name}</span><span>{money(c.spend)}</span><span>{c.roas.toFixed(2)}×</span><span className={c.contribution>=0?'good':'bad'}>{money(c.contribution)}</span><span><em className={`decision d-${decisionFor(c).split(' ')[0].toLowerCase()}`}>{decisionFor(c)}</em></span></button>)}</div></div>
   <div className="card panel"><span className="kicker">DATA QUALITY</span><h3>Measurement readiness</h3><div className="checks"><div><h4>Strengths</h4>{ready.strengths.map(x=><p key={x}>✓ {x}</p>)}</div><div><h4>Blockers / caveats</h4>{ready.issues.map(x=><p key={x} className="warn">! {x}</p>)}</div></div><div className="notice"><b>Honesty layer</b><br/>A high readiness score means the file is analyzable. It does <u>not</u> upgrade descriptive data into causal evidence.</div></div></section>
   <section className="grid2"><div className="card panel"><span className="kicker">RECONCILIATION</span><h3>Platform vs internal reality</h3>{rec.available?<><div className="recon"><div><span>Platform-reported</span><b>{money(rec.platform)}</b></div><div><span>Internal observed</span><b>{money(rec.internal)}</b></div><div><span>{rec.complete?'Gap':'Coverage'}</span><b className={rec.complete&&rec.pct!==null&&Math.abs(rec.pct)>.1?'bad':''}>{rec.complete&&rec.pct!==null?pct(rec.pct):pct(rec.coverage)}</b></div></div><p className="muted">{rec.complete?'A discrepancy is a measurement warning, not proof that either source is wrong.':'Internal revenue is partial. The app refuses to calculate a misleading aggregate platform-vs-internal gap.'}</p></>:<div className="empty">Add <code>internal_revenue</code> to reconcile ad-platform reporting with backend outcomes.</div>}</div>
   <div className="card panel"><span className="kicker">EXPERIMENT CHECK</span><h3>Controlled lift, only when valid</h3>{exp?<><div className="exp"><div><b>{exp.a.name}</b><span>{pct(exp.a.rate)}</span></div><div className="arrow">→</div><div><b>{exp.b.name}</b><span>{pct(exp.b.rate)}</span></div></div><p><b>{pct(exp.lift)} relative lift</b> · p={exp.p.toFixed(4)} · 95% CI of absolute difference {pct(exp.ci[0])} to {pct(exp.ci[1])}</p><div className={`notice ${exp.significant?'ok':''}`}>{exp.significant?'Statistically detectable difference. Randomization metadata is present, but instrumentation and sample-ratio health still need real-world verification.':'No statistically detectable difference at the 5% level.'}</div></>:<div className="empty">No analysis-qualified randomized 2-group experiment detected. Group labels alone are not treated as proof of randomization, and impressions are not used as a user denominator.</div>}</div></section>
   <section className="card panel"><div className="panelHead"><div><span className="kicker">SIMULATION · NOT CAUSAL</span><h3>Budget allocation sandbox</h3></div><label>Scenario budget <b>{money(budget)}</b><input aria-label="Scenario budget" type="range" min="20000" max="250000" step="5000" value={budget} onChange={e=>setBudget(+e.target.value)}/></label></div><div className="alloc">{plan.map((p:{name:string;suggested:number;confidence:string})=><div className="allocRow" key={p.name}><div><b>{p.name}</b><span>{p.confidence} confidence</span></div><div className="allocBar"><i style={{width:`${Math.min(100,p.suggested/budget*250)}%`}}/></div><strong>{money(p.suggested)}</strong></div>)}</div><div className="notice">This sandbox reweights budget only toward positive observed contribution efficiency when such campaigns exist. It is a planning heuristic—not an estimate of incremental ROAS.</div></section>
   {selected&&(()=>{const c=campaigns.find(x=>x.name===selected)!;return <section className="card drill" role="dialog" aria-modal="false" aria-label={`${c.name} campaign investigation`}><button className="close" aria-label="Close campaign investigation" onClick={()=>setSelected(null)}>×</button><span className="kicker">CAMPAIGN INVESTIGATION</span><h3>{c.name}</h3><div className="drillGrid"><div><span>Observed spend</span><b>{money(c.spend)}</b></div><div><span>Decision-basis revenue</span><b>{money(c.revenue)}</b></div><div><span>Revenue basis</span><b>{c.revenueBasis}</b></div><div><span>ROAS</span><b>{c.roas.toFixed(2)}×</b></div><div><span>CPA</span><b>{money(c.cpa)}</b></div><div><span>Contribution estimate</span><b>{money(c.contribution)}</b></div><div><span>Decision cue</span><b>{decisionFor(c)}</b></div></div><p className="muted">Decision cue combines observed economics with your gross-margin assumption. “Scale candidate” means economically interesting for further testing; it does not prove incremental lift.</p></section>})()}
  </>}
  <footer><b>Why this is not just another attribution dashboard.</b> The product starts by limiting the claim, separates platform reporting from backend outcomes, and labels facts, estimates, experiments and simulations separately.</footer>
 </main>
}
